version: '3.12.1'

services:
  app:
    build: .
    container_name: my_fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./schedule.db
      - SECRET_KEY=YOUR_SECRET_KEY
      - ECHO=True
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin
    volumes:
      - .:/app
    # command: >
    #   uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    command: >
      sh -c "python create_admin.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"